// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtcejlqidshrsopgegrh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0Y2VqbHFpZHNocnNvcGdlZ3JoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MTY0NzgsImV4cCI6MjA3NDQ5MjQ3OH0.P0JxjFRB4PG1k7Ge0xyqckM6GumCOAdqWkteET28UHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});